Connecting NESO dataset

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../database/wind_power.db")

df = pd.read_sql(
    "SELECT * FROM wind_generation_clean",
    conn
)

df.head()

              DATETIME    WIND
0  2018-01-01T00:00:00  8596.0
1  2018-01-01T00:30:00  8750.0
2  2018-01-01T01:00:00  8631.0
3  2018-01-01T01:30:00  8595.0
4  2018-01-01T02:00:00  8437.0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140256 entries, 0 to 140255
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   DATETIME  140256 non-null  object
 1   WIND      140256 non-null  float64
dtypes: float64(1), object(1)
memory usage: 2.1+ MB

Creating Timestamp

- First we format DATE from object to datatime format

In [4]:
df["DATETIME"] = pd.to_datetime(
    df["DATETIME"],
    format="mixed",
    dayfirst=True
)

In [5]:
df.head()

             DATETIME    WIND
0 2018-01-01 00:00:00  8596.0
1 2018-01-01 00:30:00  8750.0
2 2018-01-01 01:00:00  8631.0
3 2018-01-01 01:30:00  8595.0
4 2018-01-01 02:00:00  8437.0

In [7]:
df["DATETIME"].dtype

dtype('<M8[ns]')

In [10]:
df["WIND"].describe()

count    140256.000000
mean       6405.289214
std        3991.919455
min           0.000000
25%        3055.000000
50%        5816.000000
75%        9355.000000
max       18382.000000
Name: WIND, dtype: float64

In [11]:
df.to_parquet(
    "../data/interim/neso_processed/wind_generation_clean.prequet",
    index=False
)

In [12]:
df.to_csv(
    "../data/interim/neso_processed/wind_generation_clean.csv",
    index = False
)

In [1]:
import pandas as pd

In [3]:
df = pd.read_parquet(
    "../data/interim/neso_processed/wind_generation_clean.prequet"
)

In [9]:
df.head()

             DATETIME    WIND
0 2018-01-01 00:00:00  8596.0
1 2018-01-01 00:30:00  8750.0
2 2018-01-01 01:00:00  8631.0
3 2018-01-01 01:30:00  8595.0
4 2018-01-01 02:00:00  8437.0

In [13]:
df["DATETIME"].max()

Timestamp('2025-12-31 23:30:00')

Converison of 30 mins to hourly

In [14]:
hourly_df = (
    df.set_index("DATETIME")
    .resample("h")
    .agg({
        "WIND":"mean"
    }).reset_index()
)

In [15]:
hourly_df.head()

             DATETIME    WIND
0 2018-01-01 00:00:00  8673.0
1 2018-01-01 01:00:00  8613.0
2 2018-01-01 02:00:00  8418.5
3 2018-01-01 03:00:00  8299.0
4 2018-01-01 04:00:00  8197.5

In [16]:
hourly_df.to_parquet(
    "../data/interim/neso_processed/wind_generation_hourly.parquet",
    index=False
)

In [17]:
d1 = hourly_df.head(100)

In [18]:
d1.to_csv("../data/wind_generation_hourly.csv", index=False)

In [ ]:
d = pd.read_parquet(
    "../"
)