In [29]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/repd/REPD_2026.csv",
    encoding="latin1"
)

In [30]:
print(df.shape)

df.columns.tolist()

(14316, 53)

['Old Ref ID',
 'Ref ID',
 'Record Last Updated (dd/mm/yyyy)',
 'Operator (or Applicant)',
 'Site Name',
 'Technology Type',
 'Storage Type',
 'Storage Co-location REPD Ref ID',
 'Installed Capacity (MWelec)',
 'Share Community Scheme',
 'CHP Enabled',
 'CfD Allocation Round',
 'RO Banding (ROC/MWh)',
 'FiT Tariff (p/kWh)',
 'CfD Capacity (MW)',
 'Turbine Capacity (MW)',
 'No. of Turbines',
 'Height of Turbines (m)',
 'Mounting Type for Solar',
 'Development Status',
 'Development Status (short)',
 'Are they re-applying (New REPD Ref)',
 'Are they re-applying (Old REPD Ref) ',
 'Address',
 'County',
 'Region',
 'Country',
 'Post Code',
 'X-coordinate',
 'Y-coordinate',
 'Planning Authority',
 'Planning Application Reference',
 'Appeal Reference',
 'Secretary of State Reference',
 'Type of Secretary of State Intervention',
 'Judicial Review',
 'Offshore Wind Round',
 'Planning Application Submitted',
 'Planning Application Withdrawn',
 'Planning Permission Refused',
 'Appeal Lodged',
 'Appeal Withdrawn',
 'Appeal Refused',
 'Appeal Granted',
 'Planning Permission  Granted',
 'Secretary of State - Intervened',
 'Secretary of State - Refusal',
 'Secretary of State - Granted',
 'Planning Permission Expired',
 'Under Construction',
 'Operational',
 'Heat Network Ref',
 'Solar Site Area (sqm)']

In [31]:
df.head()

,Old Ref ID,Ref ID,Record Last Updated (dd/mm/yyyy),Operator (or Applicant),Site Name,Technology Type,Storage Type,Storage Co-location REPD Ref ID,Installed Capacity (MWelec),Share Community Scheme,...,Appeal Granted,Planning Permission Granted,Secretary of State - Intervened,Secretary of State - Refusal,Secretary of State - Granted,Planning Permission Expired,Under Construction,Operational,Heat Network Ref,Solar Site Area (sqm)
0,N00053B,1,16/01/2026,RWE npower,Aberthaw Power Station Biomass,Biomass (co-firing),NaN,NaN,35,NaN,...,NaN,03/09/2004,NaN,NaN,NaN,NaN,01/05/2006,01/05/2007,NaN,NaN
1,AA110,2,20/11/2017,Orsted (formerly Dong Energy) / Peel Energy,Hunterston - cofiring,Biomass (co-firing),NaN,NaN,170,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,B0730,3,20/12/2019,Scottish and Southern Energy (SSE),Ferrybridge Multifuel 2 (FM2),EfW Incineration,NaN,NaN,70,NaN,...,NaN,28/10/2015,NaN,NaN,NaN,28/10/2020,01/09/2016,20/12/2019,NaN,NaN
3,1106000,4,18/12/2003,Energy Power Resources,Thetford Biomass Power Station,Biomass (dedicated),NaN,NaN,38.5,NaN,...,NaN,05/05/1995,NaN,NaN,NaN,NaN,NaN,02/10/1998,NaN,NaN
4,,5,29/09/2005,Agrigen,Nunn Mills Road Biomass Plant,Biomass (dedicated),NaN,NaN,8.8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df["Technology Type"].value_counts()

Technology Type
Solar Photovoltaics                 7235
Wind Onshore                        2725
Battery                             2605
Anaerobic Digestion                  383
Landfill Gas                         293
Biomass (dedicated)                  286
EfW Incineration                     213
Small Hydro                          154
Advanced Conversion Technologies     128
Wind Offshore                        101
Hydrogen                              66
Large Hydro                           33
Tidal Stream                          31
Pumped Storage Hydroelectricity       18
Sewage Sludge Digestion               12
Shoreline Wave                         8
Geothermal                             6
Biomass (co-firing)                    4
Liquid Air Energy Storage              4
Fuel Cell (Hydrogen)                   3
Hot Dry Rocks (HDR)                    2
Unknown                                2
Compressed Air Energy Storage          2
Tidal Lagoon                           1
Flywheels                              1
Name: count, dtype: int64

In [33]:
wind_df = df[
    df["Technology Type"].isin(
        [
            "Wind Onshore",
            "Wind Offshore"
        ]
    )
]

In [34]:
wind_df["Development Status"].value_counts()

Development Status
Operational                       826
Planning Permission Refused       369
Planning Permission Granted       345
Planning Application Submitted    317
Planning Application Withdrawn    284
Revised                           237
Appeal Refused                    202
Abandoned                          56
Planning Permission Expired        56
Under Construction                 48
Appeal Withdrawn                   31
Appeal Granted                     29
Secretary of State - Refusal       15
Decommissioned                      8
No Application Required             2
Secretary of State - Granted        1
Name: count, dtype: int64

In [35]:
wind_df = wind_df[
    wind_df["Development Status"] == "Operational"
]

In [36]:
wind_df["Development Status"].value_counts()

Development Status
Operational    826
Name: count, dtype: int64

In [37]:
repd_clean = wind_df[
    [
        "Site Name",
        "Technology Type",
        "Installed Capacity (MWelec)",
        "Turbine Capacity (MW)",
        "No. of Turbines",
        "Height of Turbines (m)",
        "Development Status",
        "Region",
        "Country",
        "X-coordinate",
        "Y-coordinate"
    ]
]

In [38]:
repd_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 826 entries, 2013 to 10410
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Site Name                    826 non-null    object
 1   Technology Type              826 non-null    object
 2   Installed Capacity (MWelec)  826 non-null    object
 3   Turbine Capacity (MW)        813 non-null    object
 4   No. of Turbines              826 non-null    object
 5   Height of Turbines (m)       110 non-null    object
 6   Development Status           826 non-null    object
 7   Region                       826 non-null    object
 8   Country                      826 non-null    object
 9   X-coordinate                 826 non-null    object
 10  Y-coordinate                 826 non-null    object
dtypes: object(11)
memory usage: 77.4+ KB

In [39]:
repd_clean.isna().sum()

Site Name                        0
Technology Type                  0
Installed Capacity (MWelec)      0
Turbine Capacity (MW)           13
No. of Turbines                  0
Height of Turbines (m)         716
Development Status               0
Region                           0
Country                          0
X-coordinate                     0
Y-coordinate                     0
dtype: int64

In [40]:
repd_clean["Site Name"].duplicated().sum()

np.int64(2)

In [41]:
duplicates = repd_clean[
    repd_clean["Site Name"].duplicated(keep=False)
]

duplicates.sort_values("Site Name")

,Site Name,Technology Type,Installed Capacity (MWelec),Turbine Capacity (MW),No. of Turbines,Height of Turbines (m),Development Status,Region,Country,X-coordinate,Y-coordinate
3167,Glenbuck,Wind Onshore,2.3,2.3,1,109,Operational,Northern Ireland,Northern Ireland,118000,577300
3168,Glenbuck,Wind Onshore,6.9,2.3,3,109,Operational,Northern Ireland,Northern Ireland,118000,577300
2609,Hagshaw Hill Wind Farm,Wind Onshore,7.8,0.6,13,NaN,Operational,Scotland,Scotland,278980,630740
2832,Hagshaw Hill Wind Farm,Wind Onshore,7.8,0.6,13,NaN,Operational,Scotland,Scotland,278965,630750

In [42]:
repd_clean[
    repd_clean["Site Name"]
    == "Hagshaw Hill Wind Farm"
]

,Site Name,Technology Type,Installed Capacity (MWelec),Turbine Capacity (MW),No. of Turbines,Height of Turbines (m),Development Status,Region,Country,X-coordinate,Y-coordinate
2609,Hagshaw Hill Wind Farm,Wind Onshore,7.8,0.6,13,NaN,Operational,Scotland,Scotland,278980,630740
2832,Hagshaw Hill Wind Farm,Wind Onshore,7.8,0.6,13,NaN,Operational,Scotland,Scotland,278965,630750

In [43]:
repd_clean[
    repd_clean.duplicated(
        subset=[
            "Site Name",
            "Technology Type",
            "Installed Capacity (MWelec)",
            "Turbine Capacity (MW)",
            "No. of Turbines",
            "Development Status"
        ],
        keep=False
    )
]

,Site Name,Technology Type,Installed Capacity (MWelec),Turbine Capacity (MW),No. of Turbines,Height of Turbines (m),Development Status,Region,Country,X-coordinate,Y-coordinate
2609,Hagshaw Hill Wind Farm,Wind Onshore,7.8,0.6,13,NaN,Operational,Scotland,Scotland,278980,630740
2832,Hagshaw Hill Wind Farm,Wind Onshore,7.8,0.6,13,NaN,Operational,Scotland,Scotland,278965,630750

In [44]:
repd_clean = repd_clean.drop_duplicates(
    subset=[
        "Site Name",
        "Technology Type",
        "Installed Capacity (MWelec)",
        "Turbine Capacity (MW)",
        "No. of Turbines",
        "Development Status"
    ]
)

In [45]:
repd_clean.shape

(825, 11)

In [46]:
repd_clean[
    repd_clean["Site Name"]
    == "Hagshaw Hill Wind Farm"
]

,Site Name,Technology Type,Installed Capacity (MWelec),Turbine Capacity (MW),No. of Turbines,Height of Turbines (m),Development Status,Region,Country,X-coordinate,Y-coordinate
2609,Hagshaw Hill Wind Farm,Wind Onshore,7.8,0.6,13,NaN,Operational,Scotland,Scotland,278980,630740

In [56]:
import pandas as pd

repd_clean = pd.read_parquet(
    "../data/interim/repd_processed/wind_farms.parquet"
)

In [60]:
repd_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Site Name                    825 non-null    object
 1   Technology Type              825 non-null    object
 2   Installed Capacity (MWelec)  825 non-null    object
 3   Turbine Capacity (MW)        812 non-null    object
 4   No. of Turbines              825 non-null    object
 5   Height of Turbines (m)       110 non-null    object
 6   Development Status           825 non-null    object
 7   Region                       825 non-null    object
 8   Country                      825 non-null    object
 9   X-coordinate                 825 non-null    object
 10  Y-coordinate                 825 non-null    object
dtypes: object(11)
memory usage: 71.0+ KB

In [61]:
import geopandas as gpd

wind_gdf = gpd.GeoDataFrame(
    repd_clean,
    geometry=gpd.points_from_xy(
        repd_clean["X-coordinate"],
        repd_clean["Y-coordinate"]
    ),
    crs="EPSG:27700"
)

In [62]:
wind_gdf = wind_gdf.to_crs("EPSG:4326")

In [63]:
wind_gdf.head()

,Site Name,Technology Type,Installed Capacity (MWelec),Turbine Capacity (MW),No. of Turbines,Height of Turbines (m),Development Status,Region,Country,X-coordinate,Y-coordinate,geometry
0,Hywind Scotland Pilot Park (Hywind 2) Demonstr...,Wind Offshore,30,6,5,None,Operational,Offshore,Scotland,433500,846500,POINT (-1.44258 57.50746)
1,Beatrice Demonstrator,Wind Offshore,10,5,2,None,Operational,Offshore,Scotland,347955,929690,POINT (-2.88843 58.25281)
2,Burbo Bank,Wind Offshore,90,3.6,25,None,Operational,Offshore,England,321476,399706,POINT (-3.18492 53.48818)
3,Gunfleet Sands - (Demo) Extension,Wind Offshore,12,6,2,None,Operational,Offshore,England,620650,205297,POINT (1.19191 51.70301)
4,Gunfleet Sands II,Wind Offshore,64.8,3.6,18,None,Operational,Offshore,England,624262,208150,POINT (1.24592 51.72719)

In [64]:
wind_gdf.to_parquet(
    "../data/interim/repd_processed/wind_farm_crs.parquet",
    index=False
)

In [65]:
wind_gdf.to_csv(
    "../data/interim/repd_processed/wind_farm_crs.csv",
    index=False
)

In [85]:
import rasterio

with rasterio.open(
    "../data/interim/terrain_processed/uk_dem.tif"
) as dem:

    coords = [
        (point.x, point.y)
        for point in wind_gdf.geometry
    ]

    elevations = [
        val[0]
        for val in dem.sample(coords)
    ]

wind_gdf["Elevation_m"] = elevations

In [86]:
wind_gdf[
    [
        "Site Name",
        "Elevation_m"
    ]
]

                                             Site Name  Elevation_m
0    Hywind Scotland Pilot Park (Hywind 2) Demonstr...     0.000000
1                                Beatrice Demonstrator     0.000000
2                                           Burbo Bank     0.000000
3                    Gunfleet Sands - (Demo) Extension     0.000000
4                                   Gunfleet Sands II      0.000000
..                                                 ...          ...
820                            Land near Ventonteague     85.830132
821                     Limekiln Wind Farm (Extension)   121.576927
822                         Lower Rumster wind turbine    98.473915
823           Mounteneys and Cherry Rock Wind Turbines    62.805923
824                               Watsonhead Wind Farm   179.970276

[825 rows x 2 columns]

In [87]:
wind_gdf["Elevation_m"].describe()

count    825.000000
mean     169.217316
std      149.181290
min       -1.782389
25%       41.167614
50%      138.605499
75%      264.336365
max      679.998535
Name: Elevation_m, dtype: float64

In [95]:
wind_gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Site Name                    825 non-null    object
 1   Technology Type              825 non-null    object
 2   Installed Capacity (MWelec)  825 non-null    object
 3   Turbine Capacity (MW)        812 non-null    object
 4   No. of Turbines              825 non-null    object
 5   Height of Turbines (m)       110 non-null    object
 6   Development Status           825 non-null    object
 7   Region                       825 non-null    object
 8   Country                      825 non-null    object
 9   X-coordinate                 825 non-null    object
 10  Y-coordinate                 825 non-null    object
 11  geometry                     825 non-null    geometry
 12  Elevation_m                  825 non-null    float32
dtypes: float32(1), geometry(1), object(11)
memory usage: 80.7+ KB

In [88]:
wind_gdf.head()

,Site Name,Technology Type,Installed Capacity (MWelec),Turbine Capacity (MW),No. of Turbines,Height of Turbines (m),Development Status,Region,Country,X-coordinate,Y-coordinate,geometry,Elevation_m
0,Hywind Scotland Pilot Park (Hywind 2) Demonstr...,Wind Offshore,30,6,5,None,Operational,Offshore,Scotland,433500,846500,POINT (-1.44258 57.50746),0.0
1,Beatrice Demonstrator,Wind Offshore,10,5,2,None,Operational,Offshore,Scotland,347955,929690,POINT (-2.88843 58.25281),0.0
2,Burbo Bank,Wind Offshore,90,3.6,25,None,Operational,Offshore,England,321476,399706,POINT (-3.18492 53.48818),0.0
3,Gunfleet Sands - (Demo) Extension,Wind Offshore,12,6,2,None,Operational,Offshore,England,620650,205297,POINT (1.19191 51.70301),0.0
4,Gunfleet Sands II,Wind Offshore,64.8,3.6,18,None,Operational,Offshore,England,624262,208150,POINT (1.24592 51.72719),0.0

In [ ]:
wind_gdf.to_parquet(
    "../data/interim/terrain_processed/wind_farm_elevation.parquet",
    index=False
)

In [90]:
wind_gdf.to_csv(
    "../data/interim/terrain_processed/wind_farm_elevation.csv",
    index=False
)

In [80]:
import geopandas as gpd

a = gpd.read_parquet(
    "../data/interim/repd_processed/wind_farm_crs.parquet"
)

In [94]:
a.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Site Name                    825 non-null    object
 1   Technology Type              825 non-null    object
 2   Installed Capacity (MWelec)  825 non-null    object
 3   Turbine Capacity (MW)        812 non-null    object
 4   No. of Turbines              825 non-null    object
 5   Height of Turbines (m)       110 non-null    object
 6   Development Status           825 non-null    object
 7   Region                       825 non-null    object
 8   Country                      825 non-null    object
 9   X-coordinate                 825 non-null    object
 10  Y-coordinate                 825 non-null    object
 11  geometry                     825 non-null    geometry
dtypes: geometry(1), object(11)
memory usage: 77.5+ KB

In [81]:
a.head()

,Site Name,Technology Type,Installed Capacity (MWelec),Turbine Capacity (MW),No. of Turbines,Height of Turbines (m),Development Status,Region,Country,X-coordinate,Y-coordinate,geometry
0,Hywind Scotland Pilot Park (Hywind 2) Demonstr...,Wind Offshore,30,6,5,None,Operational,Offshore,Scotland,433500,846500,POINT (-1.44258 57.50746)
1,Beatrice Demonstrator,Wind Offshore,10,5,2,None,Operational,Offshore,Scotland,347955,929690,POINT (-2.88843 58.25281)
2,Burbo Bank,Wind Offshore,90,3.6,25,None,Operational,Offshore,England,321476,399706,POINT (-3.18492 53.48818)
3,Gunfleet Sands - (Demo) Extension,Wind Offshore,12,6,2,None,Operational,Offshore,England,620650,205297,POINT (1.19191 51.70301)
4,Gunfleet Sands II,Wind Offshore,64.8,3.6,18,None,Operational,Offshore,England,624262,208150,POINT (1.24592 51.72719)

In [23]:
repd_clean[
    ["Site Name", "X-coordinate", "Y-coordinate"]
].head()

                                           Site Name X-coordinate Y-coordinate
0  Hywind Scotland Pilot Park (Hywind 2) Demonstr...       433500       846500
1                              Beatrice Demonstrator       347955       929690
2                                         Burbo Bank       321476       399706
3                  Gunfleet Sands - (Demo) Extension       620650       205297
4                                 Gunfleet Sands II        624262       208150

In [24]:
with rasterio.open(
    "../data/interim/terrain_processed/uk_dem.tif"
) as dem:

    elevation = dem.read(1)

    xres = dem.res[0]
    yres = dem.res[1]