In [1]:
import numpy as np
import pandas as pd

In [2]:
vws_dataset = pd.read_parquet(
    "../data/processed/featured_data1.parquet"
)

In [3]:
vws_dataset.head()

,timestamp,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,...,wd10_sin,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos
0,2018-01-01 00:00:00,12.281535,250.820054,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,...,-0.279326,-0.279326,0,0,1,1,0.000000,1.000000,0.5,0.866025
1,2018-01-01 01:00:00,12.115093,248.852093,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,...,-0.315341,-0.315341,1,0,1,1,0.258819,0.965926,0.5,0.866025
2,2018-01-01 02:00:00,11.805504,245.666682,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,...,-0.371450,-0.371450,2,0,1,1,0.500000,0.866025,0.5,0.866025
3,2018-01-01 03:00:00,11.557783,242.461919,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,...,-0.424959,-0.424959,3,0,1,1,0.707107,0.707107,0.5,0.866025
4,2018-01-01 04:00:00,11.096890,239.026854,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,...,-0.479834,-0.479834,4,0,1,1,0.866025,0.500000,0.5,0.866025

In [4]:
#wind direction is circular and 359 and 1 degree are same so making sure the model understands
vws_dataset["wd100_sin"] = np.sin(np.radians(vws_dataset["wd100"]))
vws_dataset["wd100_cos"] = np.cos(np.radians(vws_dataset["wd100"]))

vws_dataset["wd10_sin"] = np.sin(np.radians(vws_dataset["wd10"]))
vws_dataset["wd10_cos"] = np.sin(np.radians(vws_dataset["wd10"]))

,timestamp,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,...,wd10_sin,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos
0,2018-01-01 00:00:00,12.281535,250.820054,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,...,-0.279326,-0.279326,0,0,1,1,0.000000,1.000000,5.000000e-01,0.866025
1,2018-01-01 01:00:00,12.115093,248.852093,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,...,-0.315341,-0.315341,1,0,1,1,0.258819,0.965926,5.000000e-01,0.866025
2,2018-01-01 02:00:00,11.805504,245.666682,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,...,-0.371450,-0.371450,2,0,1,1,0.500000,0.866025,5.000000e-01,0.866025
3,2018-01-01 03:00:00,11.557783,242.461919,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,...,-0.424959,-0.424959,3,0,1,1,0.707107,0.707107,5.000000e-01,0.866025
4,2018-01-01 04:00:00,11.096890,239.026854,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,...,-0.479834,-0.479834,4,0,1,1,0.866025,0.500000,5.000000e-01,0.866025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70115,2025-12-31 19:00:00,11.614135,273.050549,178.456925,1.443263,82.358868,1.260005,897.876659,0.682255,0.000064,...,0.026928,0.026928,19,2,12,365,-0.965926,0.258819,-2.449294e-16,1.000000
70116,2025-12-31 20:00:00,11.852626,272.359650,179.375989,1.434831,83.138695,1.259141,907.726745,0.648882,0.000096,...,0.010891,0.010891,20,2,12,365,-0.866025,0.500000,-2.449294e-16,1.000000
70117,2025-12-31 21:00:00,12.204287,272.688128,179.124116,1.423274,82.621244,1.258121,912.173354,0.600996,0.000137,...,0.015286,0.015286,21,2,12,365,-0.707107,0.707107,-2.449294e-16,1.000000
70118,2025-12-31 22:00:00,12.575946,274.281331,177.881503,1.420689,82.359252,1.257125,934.792189,0.612354,0.000105,...,0.036966,0.036966,22,2,12,365,-0.500000,0.866025,-2.449294e-16,1.000000
70119,2025-12-31 23:00:00,12.869051,276.649089,175.266215,1.414885,82.118600,1.256178,969.206299,0.604195,0.000083,...,0.082526,0.082526,23,2,12,365,-0.258819,0.965926,-2.449294e-16,1.000000

In [5]:
vws_dataset.head()

,timestamp,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,...,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos,wd100_cos
0,2018-01-01 00:00:00,12.281535,250.820054,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,...,-0.279326,0,0,1,1,0.000000,1.000000,0.5,0.866025,-0.328536
1,2018-01-01 01:00:00,12.115093,248.852093,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,...,-0.315341,1,0,1,1,0.258819,0.965926,0.5,0.866025,-0.360777
2,2018-01-01 02:00:00,11.805504,245.666682,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,...,-0.371450,2,0,1,1,0.500000,0.866025,0.5,0.866025,-0.412044
3,2018-01-01 03:00:00,11.557783,242.461919,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,...,-0.424959,3,0,1,1,0.707107,0.707107,0.5,0.866025,-0.462338
4,2018-01-01 04:00:00,11.096890,239.026854,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,...,-0.479834,4,0,1,1,0.866025,0.500000,0.5,0.866025,-0.514636

In [8]:
vws_dataset.drop(columns=["wd10","wd100"])

,timestamp,ws100,wind_shear,relative_humidity,air_density,blh,tcc,tp,ssrd,i10fg,...,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos,wd100_cos
0,2018-01-01 00:00:00,12.281535,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,0.0,13.781487,...,-0.279326,0,0,1,1,0.000000,1.000000,5.000000e-01,0.866025,-0.328536
1,2018-01-01 01:00:00,12.115093,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,0.0,13.967654,...,-0.315341,1,0,1,1,0.258819,0.965926,5.000000e-01,0.866025,-0.360777
2,2018-01-01 02:00:00,11.805504,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,0.0,13.612556,...,-0.371450,2,0,1,1,0.500000,0.866025,5.000000e-01,0.866025,-0.412044
3,2018-01-01 03:00:00,11.557783,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,0.0,12.992998,...,-0.424959,3,0,1,1,0.707107,0.707107,5.000000e-01,0.866025,-0.462338
4,2018-01-01 04:00:00,11.096890,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,0.0,12.466838,...,-0.479834,4,0,1,1,0.866025,0.500000,5.000000e-01,0.866025,-0.514636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70115,2025-12-31 19:00:00,11.614135,1.443263,82.358868,1.260005,897.876659,0.682255,0.000064,0.0,13.735105,...,0.026928,19,2,12,365,-0.965926,0.258819,-2.449294e-16,1.000000,0.053217
70116,2025-12-31 20:00:00,11.852626,1.434831,83.138695,1.259141,907.726745,0.648882,0.000096,0.0,14.067062,...,0.010891,20,2,12,365,-0.866025,0.500000,-2.449294e-16,1.000000,0.041172
70117,2025-12-31 21:00:00,12.204287,1.423274,82.621244,1.258121,912.173354,0.600996,0.000137,0.0,14.590686,...,0.015286,21,2,12,365,-0.707107,0.707107,-2.449294e-16,1.000000,0.046899
70118,2025-12-31 22:00:00,12.575946,1.420689,82.359252,1.257125,934.792189,0.612354,0.000105,0.0,14.951752,...,0.036966,22,2,12,365,-0.500000,0.866025,-2.449294e-16,1.000000,0.074654
70119,2025-12-31 23:00:00,12.869051,1.414885,82.118600,1.256178,969.206299,0.604195,0.000083,0.0,15.340371,...,0.082526,23,2,12,365,-0.258819,0.965926,-2.449294e-16,1.000000,0.115788

In [10]:
#dropping tsd as its correlation with nd is 0.98 also ws10
vws_dataset

,timestamp,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,...,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos,wd100_cos
0,2018-01-01 00:00:00,12.281535,250.820054,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,...,-0.279326,0,0,1,1,0.000000,1.000000,5.000000e-01,0.866025,-0.328536
1,2018-01-01 01:00:00,12.115093,248.852093,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,...,-0.315341,1,0,1,1,0.258819,0.965926,5.000000e-01,0.866025,-0.360777
2,2018-01-01 02:00:00,11.805504,245.666682,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,...,-0.371450,2,0,1,1,0.500000,0.866025,5.000000e-01,0.866025,-0.412044
3,2018-01-01 03:00:00,11.557783,242.461919,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,...,-0.424959,3,0,1,1,0.707107,0.707107,5.000000e-01,0.866025,-0.462338
4,2018-01-01 04:00:00,11.096890,239.026854,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,...,-0.479834,4,0,1,1,0.866025,0.500000,5.000000e-01,0.866025,-0.514636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70115,2025-12-31 19:00:00,11.614135,273.050549,178.456925,1.443263,82.358868,1.260005,897.876659,0.682255,0.000064,...,0.026928,19,2,12,365,-0.965926,0.258819,-2.449294e-16,1.000000,0.053217
70116,2025-12-31 20:00:00,11.852626,272.359650,179.375989,1.434831,83.138695,1.259141,907.726745,0.648882,0.000096,...,0.010891,20,2,12,365,-0.866025,0.500000,-2.449294e-16,1.000000,0.041172
70117,2025-12-31 21:00:00,12.204287,272.688128,179.124116,1.423274,82.621244,1.258121,912.173354,0.600996,0.000137,...,0.015286,21,2,12,365,-0.707107,0.707107,-2.449294e-16,1.000000,0.046899
70118,2025-12-31 22:00:00,12.575946,274.281331,177.881503,1.420689,82.359252,1.257125,934.792189,0.612354,0.000105,...,0.036966,22,2,12,365,-0.500000,0.866025,-2.449294e-16,1.000000,0.074654
70119,2025-12-31 23:00:00,12.869051,276.649089,175.266215,1.414885,82.118600,1.256178,969.206299,0.604195,0.000083,...,0.082526,23,2,12,365,-0.258819,0.965926,-2.449294e-16,1.000000,0.115788

In [11]:
vws_dataset.head()

,timestamp,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,...,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos,wd100_cos
0,2018-01-01 00:00:00,12.281535,250.820054,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,...,-0.279326,0,0,1,1,0.000000,1.000000,0.5,0.866025,-0.328536
1,2018-01-01 01:00:00,12.115093,248.852093,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,...,-0.315341,1,0,1,1,0.258819,0.965926,0.5,0.866025,-0.360777
2,2018-01-01 02:00:00,11.805504,245.666682,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,...,-0.371450,2,0,1,1,0.500000,0.866025,0.5,0.866025,-0.412044
3,2018-01-01 03:00:00,11.557783,242.461919,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,...,-0.424959,3,0,1,1,0.707107,0.707107,0.5,0.866025,-0.462338
4,2018-01-01 04:00:00,11.096890,239.026854,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,...,-0.479834,4,0,1,1,0.866025,0.500000,0.5,0.866025,-0.514636

In [12]:
vws_dataset["hour"] = vws_dataset["timestamp"].dt.hour
vws_dataset["day_of_week"] = vws_dataset["timestamp"].dt.dayofweek
vws_dataset["month"] = vws_dataset["timestamp"].dt.month
vws_dataset["day_of_year"] = vws_dataset["timestamp"].dt.dayofyear

In [13]:
vws_dataset["hour_sin"] = np.sin(2*np.pi*vws_dataset["hour"]/24)
vws_dataset["hour_cos"] = np.cos(2*np.pi*vws_dataset["hour"]/24)

vws_dataset["month_sin"] = np.sin(2*np.pi*vws_dataset["month"]/12)
vws_dataset["month_cos"] = np.cos(2*np.pi*vws_dataset["month"]/12)

In [14]:
vws_dataset.head(5)

,timestamp,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,...,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos,wd100_cos
0,2018-01-01 00:00:00,12.281535,250.820054,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,...,-0.279326,0,0,1,1,0.000000,1.000000,0.5,0.866025,-0.328536
1,2018-01-01 01:00:00,12.115093,248.852093,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,...,-0.315341,1,0,1,1,0.258819,0.965926,0.5,0.866025,-0.360777
2,2018-01-01 02:00:00,11.805504,245.666682,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,...,-0.371450,2,0,1,1,0.500000,0.866025,0.5,0.866025,-0.412044
3,2018-01-01 03:00:00,11.557783,242.461919,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,...,-0.424959,3,0,1,1,0.707107,0.707107,0.5,0.866025,-0.462338
4,2018-01-01 04:00:00,11.096890,239.026854,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,...,-0.479834,4,0,1,1,0.866025,0.500000,0.5,0.866025,-0.514636

In [32]:
vws_dataset.to_parquet(
    "../data/processed/featured_data1.parquet",
    index=False
)

In [33]:
vws_dataset.to_csv(
    "../data/processed/featured_data1.csv",
    index=False
)

In [15]:
gradient_data = vws_dataset
rnn_data = vws_dataset

In [ ]:
#creating lag feature for xgboost and light bgm
lag_features = [
    "ws100",
    "wind_shear",
    "i10fg",
    "relative_humidity",
    "air_density",
    "blh",
    "tcc",
    "tp"
]

for col in lag_features:
    gradient_data[f"{col}_lag_1"] = gradient_data[col].shift(1)

    gradient_data[f"{col}_lag_24"] = gradient_data[col].shift(24)

In [39]:
gradient_data["gen_lag_1"] = gradient_data["EMBEDDED_WIND_GENERATION"].shift(1)

gradient_data["gen_lag_24"] = gradient_data["EMBEDDED_WIND_GENERATION"].shift(24)

gradient_data["gen_lag_168"] = gradient_data["EMBEDDED_WIND_GENERATION"].shift(168)

In [40]:
rolling_feature = [
    "ws100",
    "EMBEDDED_WIND_GENERATION"
]

for col in rolling_feature:

    gradient_data[f"{col}_roll_mean_6"] = (gradient_data[col].rolling(6).mean())

    gradient_data[f"{col}_roll_mean_24"] = (gradient_data[col].rolling(24).mean())

    gradient_data[f"{col}_roll_std_6"] = (gradient_data[col].rolling(6).std())

    gradient_data[f"{col}_roll_std_24"] = (gradient_data[col].rolling(24).std())

In [41]:
gradient_data = gradient_data.dropna()

In [42]:
gradient_data.head(5)

,timestamp,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,...,gen_lag_24,gen_lag_168,ws100_roll_mean_6,ws100_roll_mean_24,ws100_roll_std_6,ws100_roll_std_24,EMBEDDED_WIND_GENERATION_roll_mean_6,EMBEDDED_WIND_GENERATION_roll_mean_24,EMBEDDED_WIND_GENERATION_roll_std_6,EMBEDDED_WIND_GENERATION_roll_std_24
168,2018-01-08 00:00:00,9.571489,123.458168,203.488319,1.526059,75.408284,1.290310,569.226360,0.233086,1.373419e-07,...,1562.0,3034.5,9.158079,8.100432,0.429500,0.681281,1778.416667,1661.520833,78.304161,115.082247
169,2018-01-08 01:00:00,9.729268,123.341758,203.587791,1.532622,75.457265,1.290216,575.803520,0.221591,1.771737e-07,...,1543.0,2922.5,9.367930,8.178694,0.319738,0.755249,1817.083333,1676.541667,71.974590,122.243869
170,2018-01-08 02:00:00,9.836440,122.082163,210.218073,1.547403,75.088646,1.289881,572.804656,0.207851,1.537921e-07,...,1522.5,2891.0,9.534459,8.259840,0.237768,0.824234,1860.583333,1695.250000,73.529189,131.640733
171,2018-01-08 03:00:00,10.086009,120.790874,208.043154,1.549158,74.343305,1.289486,571.585691,0.261382,2.836549e-07,...,1521.0,2803.0,9.687474,8.353271,0.249817,0.898732,1909.416667,1717.541667,90.983194,145.426652
172,2018-01-08 04:00:00,10.206726,121.037677,196.283602,1.549389,74.309033,1.289142,575.488294,0.312405,6.233502e-07,...,1534.5,2638.5,9.820733,8.456012,0.281620,0.964242,1953.250000,1739.750000,93.642271,156.532328

In [44]:
gradient_data.drop(columns=["timestamp", "CAPACITY_FACTOR", "EMBEDDED_WIND_CAPACITY", "ND"])

,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,ssrd,...,gen_lag_24,gen_lag_168,ws100_roll_mean_6,ws100_roll_mean_24,ws100_roll_std_6,ws100_roll_std_24,EMBEDDED_WIND_GENERATION_roll_mean_6,EMBEDDED_WIND_GENERATION_roll_mean_24,EMBEDDED_WIND_GENERATION_roll_std_6,EMBEDDED_WIND_GENERATION_roll_std_24
168,9.571489,123.458168,203.488319,1.526059,75.408284,1.290310,569.226360,0.233086,1.373419e-07,0.0,...,1562.0,3034.5,9.158079,8.100432,0.429500,0.681281,1778.416667,1661.520833,78.304161,115.082247
169,9.729268,123.341758,203.587791,1.532622,75.457265,1.290216,575.803520,0.221591,1.771737e-07,0.0,...,1543.0,2922.5,9.367930,8.178694,0.319738,0.755249,1817.083333,1676.541667,71.974590,122.243869
170,9.836440,122.082163,210.218073,1.547403,75.088646,1.289881,572.804656,0.207851,1.537921e-07,0.0,...,1522.5,2891.0,9.534459,8.259840,0.237768,0.824234,1860.583333,1695.250000,73.529189,131.640733
171,10.086009,120.790874,208.043154,1.549158,74.343305,1.289486,571.585691,0.261382,2.836549e-07,0.0,...,1521.0,2803.0,9.687474,8.353271,0.249817,0.898732,1909.416667,1717.541667,90.983194,145.426652
172,10.206726,121.037677,196.283602,1.549389,74.309033,1.289142,575.488294,0.312405,6.233502e-07,0.0,...,1534.5,2638.5,9.820733,8.456012,0.281620,0.964242,1953.250000,1739.750000,93.642271,156.532328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70115,11.614135,273.050549,178.456925,1.443263,82.358868,1.260005,897.876659,0.682255,6.449366e-05,0.0,...,1130.0,2427.0,10.652537,8.338487,0.790154,1.636556,2917.666667,1706.833333,426.400711,807.700933
70116,11.852626,272.359650,179.375989,1.434831,83.138695,1.259141,907.726745,0.648882,9.629875e-05,0.0,...,1112.5,2445.5,11.031170,8.566818,0.714592,1.729977,3152.500000,1816.562500,430.620483,897.357356
70117,12.204287,272.688128,179.124116,1.423274,82.621244,1.258121,912.173354,0.600996,1.374891e-04,0.0,...,1069.5,2473.0,11.400567,8.809141,0.635969,1.816731,3388.083333,1936.500000,411.112931,981.578996
70118,12.575946,274.281331,177.881503,1.420689,82.359252,1.257125,934.792189,0.612354,1.051801e-04,0.0,...,1026.5,2578.0,11.753956,9.075669,0.593557,1.882177,3585.583333,2062.187500,389.604725,1050.683926
70119,12.869051,276.649089,175.266215,1.414885,82.118600,1.256178,969.206299,0.604195,8.318105e-05,0.0,...,986.5,2687.0,12.078901,9.350741,0.578782,1.935555,3758.583333,2193.708333,363.080765,1106.268227

In [ ]:
gradient_data.to_parquet(
    "../data/processed/gradient_data.csv",
    index=False
)

In [16]:
rnn_data = vws_dataset.copy()

In [17]:
rnn_data.drop(columns=["CAPACITY_FACTOR", "EMBEDDED_WIND_CAPACITY", "ND"])

,timestamp,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,...,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos,wd100_cos
0,2018-01-01 00:00:00,12.281535,250.820054,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,...,-0.279326,0,0,1,1,0.000000,1.000000,5.000000e-01,0.866025,-0.328536
1,2018-01-01 01:00:00,12.115093,248.852093,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,...,-0.315341,1,0,1,1,0.258819,0.965926,5.000000e-01,0.866025,-0.360777
2,2018-01-01 02:00:00,11.805504,245.666682,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,...,-0.371450,2,0,1,1,0.500000,0.866025,5.000000e-01,0.866025,-0.412044
3,2018-01-01 03:00:00,11.557783,242.461919,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,...,-0.424959,3,0,1,1,0.707107,0.707107,5.000000e-01,0.866025,-0.462338
4,2018-01-01 04:00:00,11.096890,239.026854,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,...,-0.479834,4,0,1,1,0.866025,0.500000,5.000000e-01,0.866025,-0.514636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70115,2025-12-31 19:00:00,11.614135,273.050549,178.456925,1.443263,82.358868,1.260005,897.876659,0.682255,0.000064,...,0.026928,19,2,12,365,-0.965926,0.258819,-2.449294e-16,1.000000,0.053217
70116,2025-12-31 20:00:00,11.852626,272.359650,179.375989,1.434831,83.138695,1.259141,907.726745,0.648882,0.000096,...,0.010891,20,2,12,365,-0.866025,0.500000,-2.449294e-16,1.000000,0.041172
70117,2025-12-31 21:00:00,12.204287,272.688128,179.124116,1.423274,82.621244,1.258121,912.173354,0.600996,0.000137,...,0.015286,21,2,12,365,-0.707107,0.707107,-2.449294e-16,1.000000,0.046899
70118,2025-12-31 22:00:00,12.575946,274.281331,177.881503,1.420689,82.359252,1.257125,934.792189,0.612354,0.000105,...,0.036966,22,2,12,365,-0.500000,0.866025,-2.449294e-16,1.000000,0.074654
70119,2025-12-31 23:00:00,12.869051,276.649089,175.266215,1.414885,82.118600,1.256178,969.206299,0.604195,0.000083,...,0.082526,23,2,12,365,-0.258819,0.965926,-2.449294e-16,1.000000,0.115788

In [18]:
rnn_data = rnn_data.drop(columns=["timestamp"])

In [19]:
rnn_data

,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,ssrd,...,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos,wd100_cos
0,12.281535,250.820054,196.219967,1.477310,85.497575,1.221705,963.648702,0.865433,0.000137,0.0,...,-0.279326,0,0,1,1,0.000000,1.000000,5.000000e-01,0.866025,-0.328536
1,12.115093,248.852093,198.381376,1.485777,84.710206,1.222602,978.021734,0.768974,0.000084,0.0,...,-0.315341,1,0,1,1,0.258819,0.965926,5.000000e-01,0.866025,-0.360777
2,11.805504,245.666682,201.805059,1.493257,84.066922,1.223426,946.694984,0.637181,0.000076,0.0,...,-0.371450,2,0,1,1,0.500000,0.866025,5.000000e-01,0.866025,-0.412044
3,11.557783,242.461919,205.148087,1.499402,84.011453,1.224199,902.616008,0.660511,0.000086,0.0,...,-0.424959,3,0,1,1,0.707107,0.707107,5.000000e-01,0.866025,-0.462338
4,11.096890,239.026854,208.674549,1.496604,84.741920,1.224817,845.336124,0.651387,0.000078,0.0,...,-0.479834,4,0,1,1,0.866025,0.500000,5.000000e-01,0.866025,-0.514636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70115,11.614135,273.050549,178.456925,1.443263,82.358868,1.260005,897.876659,0.682255,0.000064,0.0,...,0.026928,19,2,12,365,-0.965926,0.258819,-2.449294e-16,1.000000,0.053217
70116,11.852626,272.359650,179.375989,1.434831,83.138695,1.259141,907.726745,0.648882,0.000096,0.0,...,0.010891,20,2,12,365,-0.866025,0.500000,-2.449294e-16,1.000000,0.041172
70117,12.204287,272.688128,179.124116,1.423274,82.621244,1.258121,912.173354,0.600996,0.000137,0.0,...,0.015286,21,2,12,365,-0.707107,0.707107,-2.449294e-16,1.000000,0.046899
70118,12.575946,274.281331,177.881503,1.420689,82.359252,1.257125,934.792189,0.612354,0.000105,0.0,...,0.036966,22,2,12,365,-0.500000,0.866025,-2.449294e-16,1.000000,0.074654
70119,12.869051,276.649089,175.266215,1.414885,82.118600,1.256178,969.206299,0.604195,0.000083,0.0,...,0.082526,23,2,12,365,-0.258819,0.965926,-2.449294e-16,1.000000,0.115788

In [72]:
rnn_data.select_dtypes(exclude=["number"])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[70120 rows x 0 columns]

In [78]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled_data = pd.DataFrame(
    scaler.fit_transform(rnn_data),
    columns=rnn_data.columns,
    index=rnn_data.index
)

In [79]:
scaled_data

,ws100,wd100,wd10,wind_shear,relative_humidity,air_density,blh,tcc,tp,ssrd,...,wd10_sin,wd10_cos,hour,day_of_week,month,day_of_year,hour_sin,hour_cos,month_sin,month_cos
0,0.515667,0.703012,0.572813,0.056259,0.735995,0.360100,0.478289,0.864849,0.065699,0.0,...,0.360337,0.360337,0.000000,0.000000,0.0,0.00000,0.500000,1.000000,0.75,0.933013
1,0.507834,0.696917,0.579445,0.057451,0.719089,0.367003,0.485738,0.767971,0.040514,0.0,...,0.342330,0.342330,0.043478,0.000000,0.0,0.00000,0.629410,0.982963,0.75,0.933013
2,0.493266,0.687052,0.589950,0.058504,0.705277,0.373349,0.469502,0.635606,0.036394,0.0,...,0.314275,0.314275,0.086957,0.000000,0.0,0.00000,0.750000,0.933013,0.75,0.933013
3,0.481609,0.677127,0.600207,0.059369,0.704086,0.379302,0.446658,0.659038,0.041470,0.0,...,0.287520,0.287520,0.130435,0.000000,0.0,0.00000,0.853553,0.853553,0.75,0.933013
4,0.459920,0.666489,0.611028,0.058975,0.719770,0.384059,0.416972,0.649874,0.037628,0.0,...,0.260083,0.260083,0.173913,0.000000,0.0,0.00000,0.933013,0.750000,0.75,0.933013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70115,0.484260,0.771860,0.518311,0.051466,0.668602,0.654934,0.444201,0.680876,0.031011,0.0,...,0.513464,0.513464,0.826087,0.333333,1.0,0.99726,0.017037,0.629410,0.50,1.000000
70116,0.495483,0.769720,0.521131,0.050279,0.685346,0.648279,0.449306,0.647358,0.046304,0.0,...,0.505445,0.505445,0.869565,0.333333,1.0,0.99726,0.066987,0.750000,0.50,1.000000
70117,0.512032,0.770737,0.520358,0.048652,0.674236,0.640433,0.451611,0.599264,0.066110,0.0,...,0.507643,0.507643,0.913043,0.333333,1.0,0.99726,0.146447,0.853553,0.50,1.000000
70118,0.529521,0.775672,0.516545,0.048288,0.668610,0.632761,0.463333,0.610671,0.050575,0.0,...,0.518483,0.518483,0.956522,0.333333,1.0,0.99726,0.250000,0.933013,0.50,1.000000
70119,0.543314,0.783005,0.508521,0.047471,0.663443,0.625472,0.481169,0.602477,0.039997,0.0,...,0.541263,0.541263,1.000000,0.333333,1.0,0.99726,0.370590,0.982963,0.50,1.000000

In [20]:
rnn_data.to_parquet(
    "../data/processed/rnn_data.parquet"
)

In [87]:
%reset